#################################
# NATS Transporter for Services #
#################################
apiVersion: v1
kind: Pod
metadata:
  name: nats
  labels:
    app: nats
spec:
  containers:
    - name: nats
      image: nats

---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - port: 4222
      nodePort: 32222
  type: LoadBalancer

---
#################################
# Wrappy Core Service           #
#################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrappy-core
  labels:
    app: wrappy-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wrappy-core
  template:
    metadata:
      labels:
        app: wrappy-core
    spec:
      containers:
        - name: wrappy-core
          image: $DEPLOYMENT_IMAGE
          imagePullPolicy: Always
          env:
            - name: SERVICEDIR
              value: services
            - name: SERVICES
              value: core
            - name: TRANSPORTER
              value: nats://nats:4222

---
#################################
# Wrappy API GAteway Service    #
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrappy-gateway
  labels:
    app: wrappy-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wrappy-gateway
  template:
    metadata:
      labels:
        app: wrappy-gateway
    spec:
      containers:
        - name: wrappy-gateway
          image: $DEPLOYMENT_IMAGE
          imagePullPolicy: Always
          env:
            - name: SERVICEDIR
              value: services
            - name: SERVICES
              value: gateway
            - name: TRANSPORTER
              value: nats://nats:4222
          ports:
            - containerPort: 3000

---
#################################
# K8S Service for API Gateway   #
#################################
apiVersion: v1
kind: Service
metadata:
  name: wrappy-service
spec:
  selector:
    app: wrappy-gateway

  ports:
    - name: http
      port: 3000
      nodePort: 30000

  type: LoadBalancer

---
#################################
# K8S Ingress for API Gateway   #
#################################
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wrappy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: wrappy-gateway
              servicePort: 3000
